### PR TITLE
changed namespace back

### PR DESCRIPTION
**Pull request by leahnp**
ingress having a problem with longer service name `$ kubectl create -f ingress.yaml 
The Ingress "crashreporter" is invalid: spec.rules[0].http.backend.serviceName: Invalid value: "elasticsearch.kube-logging": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123')` 

reverting so I can just use "elasticsearch", which works.

### CODE REVIEW

**Comment by mikeln** [comment]
wow, that is lame.  they don't allow period....

**Comment by leahnp** [comment]
@mikeln ya...seems like there might be a fix (according to some issues online), but we can't reap the benefits until we update the cluster. So for now I just need to move forward - do you mind merging?

**Comment by mikeln** [comment]
are we sure there isn't a `namespace:`  key in the `backend:` block?

**Comment by leahnp** [comment]
not that I can see from the docs.

**Comment by mikeln** [comment]
looks like they added it: https://github.com/kubernetes/kubernetes/issues/17642

**Comment by leahnp** [comment]
Hmmm, I get:
```$ kubectl create -f ingress.yaml 
error: error validating "ingress.yaml": error validating data: found invalid field namespace for v1beta1.IngressBackend; if you choose to ignore these errors, turn validation off with --validate=false```

**Comment by mikeln** [comment]
I just saying we want to use namespacing as much as possible...  

it maybe `apiVersion: extensions/v1beta1` versus just `v1beta1`.

**Comment by leahnp** [comment]
Ya, I am using: `apiVersion: extensions/v1beta1`

**Comment by mikeln** [comment]
ok, so the validation error comes from the similar code kubectl/helm use to validate the schema...I wonder what version that is really in.... anyway. I'll OK this.   But we really need to get this namespace stuff working .

**Comment by leahnp** [comment]
@mikeln agreed, it is part of the upcoming logging work

**Pull request merged**
