### PR TITLE
updated name validation to 63 chars

### PR DESCRIPTION
**Pull request by DStorck**
as of k8s 1.4, service names can now be 63 chars instead of 24
https://github.com/fabric8io/fabric8-maven-plugin/pull/857

### CODE REVIEW

**Comment by NathanZook** [comment]
At the risk of getting a lot of hate, I don't like magic numbers.  63 is a specific value that we are placing for a specific reason.  It should be set in one place and referenced everywhere.

**Comment by NathanZook** [comment]
The more I think about this, the more I wonder about going a different direction entirely.  Why is the name being changed all over the place like this?  What happens if someone adds another use of the name & does not know to include the change?  What if someone creates three clusters, with first 64 characters of the name the same, but ending in -dev, -prod, and -test?  The term "validate" was used when discussing this matter in standup.  Should we not fail if the name is not valid?

**Comment by leahnp** [comment]
Nathan's comment about a variable for the max length is interesting - I guess I would consider how often this number might be changed by Kubernetes. If it is prone to change often, a variable would be nice, but if it rarely changes, I think we can just assume this maximum will be known and understood. We could add something in the documentation about it, that might give users another opportunity to understand what's going on. Otherwise LGTM.

**Comment by NathanZook** [comment]
I realize I should have been a bit more precise.   We should validate the length of the name.  Once, when the config is being ingested.  After such validation (and the variable/constant distinction is greatly lessen), all of the filtering that we currently have should be removed.

**Comment by coffeepac** [comment]
k2-charts will not only be consumed by k2.  they are designed to be stand alone, general purpose items.  each chart needs it have it own set of checks.

the _helpers.tpl file makes me deeply unhappy but it is current Best Practice from the Helm folks.

**Comment by davidewatson** [comment]
I wonder if using a (new to me) [requirements.txt](https://github.com/kubernetes/helm/blob/master/docs/charts.md) file would allow this value to specified in a single place and reduce the duplication of helpers. I don't think this should block this work.

**Comment by DStorck** [comment]
Yes, the service name needs to get validated in k2-charts.  The jsonschema doens't have a chance to validate it.  I agree with @dwat that the repetition is ridiculous, but I don't see a way around it at the moment.

**Comment by NathanZook** [comment]
A custom filter that simply bombs if the name is too long would eliminate the magic number problem, eliminate the security bomb problem, and make the 20 sources of truth problem significantly less fragile.

Silently changing user input in the fashion that we have been doing is deeply problematic.  Extending the limit to 63 does not address the problem.

**Comment by NathanZook** [comment]
https://github.com/sapcc/openstack-helm has an example of custom functions being defined across charts.  `default .Chart.Name .Values.nameOverride | valid_cluster_name_or_panic` appearing 30 times would appear to be the best we can do.

**Comment by DStorck** [comment]
so it seems like we have three options at this point : 
 - merge this and decided we are done with this issue 
 - merge this and write up another issue to refactor the way we validate service names altogether
 - close this without merging, write up another issue to refactor 

For now, this work shouldn't harm anything, and I don't know how high up on the todo list a refactor like this is, so I'm going to suggest closing it and writing up another ticket. Thoughts?

**Comment by davidewatson** [comment]
Please open a ticket and reference this one.

**Pull request merged**
